[package]
name = "fs_notify"
version = "0.1.0"
edition = "2021"

[lib]
name = "fs_notify"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.2"
notify = "7.0.0"
notify-debouncer-mini = "0.5.0"
tokio = { version = "1.0", features = ["sync", "rt"] }
once_cell = "1.19"