[package]
name = "fs_notify"
version = "0.1.0"
edition = "2021"

[lib]
name = "fs_notify"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.2"
notify = "6.1.1"
tokio = { version = "1.0", features = ["sync", "rt"] }